export class AddToCart {
    public cartId? : string;
    public retailerName: string;
    public retailerId: number;
    public productName: string;
    public productId: string;
    public quantity: number;
    public price: number;
    public productImage: string;
    public inStock: number;
    public retailerReturns: string;
    public shipProfileId: string;
    public productDescription: string;
    public taxCode: string;
    public productSKUCode: string;
    public productUPCCode: number;
    public label: string;
    public userId: string;
    public shippingHeight: number;
    public shippingLength: number;
    public shippingWeight: number;
    public shippingWidth: number;
    public orderFrom: string;
    public productHierarchy: string;
    public productAttributes: string;
    public retailerIntegrationMethod: string;
    public channelAdviosorProductSku: string;
    public channelAdviosorRetailerSku: string;
    public leadTimeToShip : number;
    public offerMade?:boolean;
    public offerCreatedDate?: Date;
}